knn:
  n_neighbors: [15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
  p: [1, 2]
  weights: ['uniform', 'distance']
  metric: ['euclidean', 'manhattan', 'minkowski']

decision_tree:
  max_depth: [5, 10, 20, 25]
  min_samples_leaf: [10, 20, 50, 100, 120]
  criterion: ['gini', 'entropy']

random_forest:
  n_estimators: [1800]
  max_features: ['sqrt', 'log2']